# Generated by Django 5.1.5 on 2025-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Mobile', models.CharField(default='', max_length=50)),
                ('Gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], default='', max_length=128)),
                ('Email', models.CharField(default='', max_length=20)),
                ('Event', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Mobile', models.IntegerField(default='')),
                ('Education', models.CharField(default='', max_length=80)),
                ('Email', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
